theme: jekyll-theme-minimal
title: Yuchuan Wang's Articles for Coding
SEOTitle: 王玉川的代码笔记与实验
description: 记录记录
keyword: "性能优化, CPU缓存, 高性能"
header-img: img/avatar.jpg
email: yuchuan.wang@gmail.com

nav:
- name: Home
  link: /
- name: About
  link: /about.html
