theme: jekyll-theme-minimal
title: Yuchuan Wang's Articles for Coding
SEOTitle: 王玉川的代码笔记与实验
description: 记录记录
keyword: "性能优化, CPU缓存, 高性能"
header-img: img/avatar.jpg
email: yuchuan.wang@gmail.com

toc:
  - title: Group 1
    subfolderitems:
      - page: Thing 1
        url: /thing1.html
      - page: Thing 2
        url: /thing2.html
      - page: Thing 3
        url: /thing3.html
  - title: Group 2
    subfolderitems:
      - page: Piece 1
        url: /piece1.html
      - page: Piece 2
        url: /piece2.html
      - page: Piece 3
        url: /piece3.html
        
