theme: jekyll-theme-minimal
title: 编程小记
description: 记录一些工作学习时的代码、工具与思考
keyword: "性能优化 CPU缓存 高性能 网络 perf ebpf bcc"
logo: /assets/img/avatar.jpg
email: yuchuan.wang@gmail.com
show_downloads: false
color-scheme: auto
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jemoji
  - jekyll-remote-theme


# https://github.com/github/pages-gem/issues/399#issuecomment-301827749
# When running locally, we run into the following error —
# GitHub Metadata: No GitHub API authentication could be found. Some fields may be missing or have incorrect data.
# adding this avoids it
github: [metadata]

cdn:
  jsdelivr:
    enabled: true
